package com.project.shopapp.model;

public enum PrivilegeType {
    VIEW_PRODUCTS,
    PLACE_ORDERS,
    VIEW_ORDER_HISTORY,
    UPDATE_ACCOUNT_INFORMATION,
    PROCESS_REFUNDS,
    UPDATE_ORDER_STATUS,
    MANAGE_PRODUCT_INVENTORY,
    UPDATE_PRODUCT_INFORMATION,
    VIEW_SALES_REPORTS,
    CREATE_PROMOTIONS,
    UPDATE_PROMOTIONS,
    MANAGE_USER_ROLES,
    VIEW_SYSTEM_LOGS,
    UPDATE_SYSTEM_SETTINGS,
    MANAGE_PRODUCT_CATEGORIES
}
